### ISSUE TITLE
apt lock

### ISSUE THREAD

**Issue by Mike-Dax** [gocd/docker-gocd-agent-ubuntu-18.04#1]
Hello,

When I run:

```
apt -qq update
```

I get this error:

```
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
```

With both `v19.8.0` and `v19.7.0`. 

`v19.1.0` seems to work however, I haven't tested all versions in between.

**Comment by arvindsv** [comment]
Since 19.6.0 ([release notes](https://www.gocd.org/releases/#19-6-0)), agent Docker containers run as non-root.

Something like:

```
d run -it -u 0 gocd/gocd-agent-ubuntu-18.04:v19.6.0 bash
```

should give you a root shell. There's a [blog post](https://www.gocd.org/2019/06/25/GoCD-non-root-containers/) about it, linked from the release notes mentioned above.

Based on this, I'll close this issue for now. Can reopen it later if needed. Thank you!
